#!/usr/bin/env python

from common import get_db_cursor, database_name, user, slave, slave_configured_path

cursor = get_db_cursor()
try:
    cursor.execute("revoke all privileges on `%s`.* from `%s`" % (database_name, user))
    print "revoked privileges for `%s` on database `%s`" % (user, database_name)
except Exception as e:
    print "revoking failed, possibly incomplete relation.[%s]" % (e)

if slave and slave_configured:
    os.unlink(slave_configured_path)
