#!/bin/bash

add-apt-repository -y ppa:charmers/charm-helpers
apt-get update
apt-get install -y debconf-utils python-mysqldb uuid augeas-tools augeas-lenses pwgen dnsutils charm-helper-sh || exit 1

PASSFILE=/var/lib/juju/mysql.passwd
if ! [ -f $PASSFILE ] ; then
  uuid > $PASSFILE
fi
PASSWORD=`cat $PASSFILE`

echo mysql-server-5.1 mysql-server/root_password password $PASSWORD | debconf-set-selections
echo mysql-server-5.1 mysql-server/root_password_again password $PASSWORD | debconf-set-selections

apt-get -y install -qq mysql-server
