#!/bin/sh
#
# Master side of master/slave replication

set -e

ROOTARGS="-uroot -p`cat /var/lib/ensemble/mysql.passwd`"
snapdir=/var/www/snaps
mkdir -p $snapdir
apt-get -y install apache2
# disable wide-open access (restrict to each db IP)
allowline=`augtool get /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]/directive[4]/arg[2]`
if [ "$allowline" = "/files/etc/apache2/sites-available/default/VirtualHost/Directory[2]/directive[4]/arg[2] = all" ] ; then
  # disable allow from all
  augtool -b <<EOF
  defvar webroot /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]
  rm \$webroot/directive[4]
  save
EOF
  service apache2 reload
fi

# TODO: settings.. make mmin tunable as it is highly subjective
recent_backup=`find $snapdir -name 'replication_seed.*.sql.gz' -mmin -60|head -1`
if [ -z "$recent_backup" ] ; then
    name=replication_seed.`date +%Y%m%d%H%M%S`.sql.gz
    echo `date`: Creating snapshot $recent_backup
    # Assumes transactional storage -- MyISAM please GO AWAY
    mysqldump $ROOTARGS --all-databases --single-transaction --master-data |gzip>$snapdir/$name
    # Make sure webserver can serve it
else
    name=`basename $recent_backup`
fi
chown -v -R www-data.www-data /var/www

remote_host=`relation-get hostname`
test -n "$remote_host" || exit 1
remote_ip=`dig +short $remote_host`
pass=`pwgen -s 16`
augtool -b <<EOF
defvar webroot /files/etc/apache2/sites-available/default/VirtualHost/Directory[2]
set \$webroot/directive[last()+1] allow
set \$webroot/directive[last()]/arg[1] from
set \$webroot/directive[last()]/arg[2] $remote_ip
save
EOF
service apache2 reload
mysql $ROOTARGS -e "GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO \`$ENSEMBLE_REMOTE_UNIT\`@\`$remote_ip\` IDENTIFIED BY '$pass'"
relation-set dumpurl=/snaps/$name \
                     user=$ENSEMBLE_REMOTE_UNIT \
                     password=$pass \
                     hostname=`hostname -f` \
                     port=3306
