#!/bin/bash
DATABASE=`relation-get database`
DB_USER=`echo $ENSEMBLE_REMOTE_UNIT | cut -d/ -f1`
REMOTE_HOST=`relation-get hostname`
REMOTE_IP=`relation-get ip`

ensemble-log "shared-db departed"


cleanup_grant() {
  mysql -u root -p$(cat /var/lib/ensemble/mysql.passwd) \
    -e "DROP FROM user WHERE user='$DB_USER' AND HOST='$REMOTE_IP'" mysql
}

ensemble-log "Cleaned out GRANT for $DB_USER@$REMOTE_IP"
echo "Cleaned out GRANT for $DB_USER@$REMOTE_IP" >>/tmp/log
