#!/bin/bash
#
# Common utility functions used for hooks in shared-db-relations
#
# Notes:
#   - /var/lib/juju/mysql.passwd is created during install hook
#
# Author: Adam Gandelman <adam.gandelman@canonical.com>

DEFAULT_ETH=$(ip route  | grep default | awk '{ print $5 }')

database_exists() {
  mysql -u root -p$(cat /var/lib/juju/mysql.passwd) \
    -NBe "SHOW DATABASES" | grep $DATABASE >/dev/null
}

create_database() {
  juju-log "mysql - shared-db: Creating database $DATABASE"
  mysql -u root -p$(cat /var/lib/juju/mysql.passwd) \
    -NBe "CREATE DATABASE $DATABASE" >/dev/null
}

grant_exists() {
  [[ $(mysql -u root -p$(cat /var/lib/juju/mysql.passwd) \
    -NBe "SELECT User, Host FROM user \
            WHERE User='$DB_USER' AND Host='$REMOTE_IP'" mysql | wc -l) -gt 0 ]]
}

create_grant() {
  juju-log "mysql - shared-db: Creating grant for $DB_USER@$REMOTE_IP"
  mysql -u root -p$(cat /var/lib/juju/mysql.passwd) \
    -NBe "GRANT ALL PRIVILEGES ON $DATABASE.* TO '$DB_USER'@'$REMOTE_IP' \
          IDENTIFIED BY '$PASSWORD'"
}

cleanup_grant() {
  juju-log "mysql - shared-db: Cleaning up grant for $DB_USER@$REMOTE_IP"
  mysql -u root -p$(cat /var/lib/juju/mysql.passwd) \
    -e "DROP FROM user WHERE user='$DB_USER' AND HOST='$REMOTE_IP'" mysql
}

