#!/bin/bash

DATABASE=`relation-get database`
DB_USER=`echo $ENSEMBLE_REMOTE_UNIT | cut -d/ -f1`
REMOTE_HOST=`relation-get hostname`
REMOTE_IP=`relation-get ip`
PASSWD_FILE="/var/lib/ensemble/mysql-$DB_USER.passwd"

DEFAULT_ETH=$(ip route  | grep default | awk '{ print $5 }')
IP=$(ifconfig  $DEFAULT_ETH | grep 'inet addr' | awk '{ print $2 }' | cut -d: -f2)

if [[ -z $DATABASE ]] || [[ -z $REMOTE_HOST ]] ; then
  exit 0
fi

if [[ ! -e $PASSWD_FILE ]] ; then
  PASSWORD=$(pwgen -s 16)
  echo $PASSWORD >$PASSWD_FILE
else
  PASSWORD=$(cat $PASSWD_FILE)
fi

database_exists() {
  mysql -u root -p$(cat /var/lib/ensemble/mysql.passwd) \
    -NBe "SHOW DATABASES" | grep $DATABASE >/dev/null
}

create_database() {
  mysql -u root -p$(cat /var/lib/ensemble/mysql.passwd) \
    -NBe "CREATE DATABASE $DATABASE" >/dev/null
}

grant_exists() {
  [[ $(mysql -u root -p$(cat /var/lib/ensemble/mysql.passwd) \
    -NBe "SELECT User, Host FROM user \
            WHERE User='$DB_USER' AND Host='$REMOTE_IP'" mysql | wc -l) -gt 0 ]]
}

create_grant() {
  mysql -u root -p$(cat /var/lib/ensemble/mysql.passwd) \
    -NBe "GRANT ALL PRIVILEGES ON $DATABASE.* TO '$DB_USER'@'$REMOTE_IP' \
          IDENTIFIED BY '$PASSWORD'"
}

if ! database_exists ; then
  echo "Creating database $DATABASE"
  create_database || exit 1
  echo "Done"
fi

if ! grant_exists ; then
  echo "Granting $DB_USER@$REMOTE_IP access to $DATABASE"
  create_grant || exit 1
fi

ensemble-log "Returning relation: db_host=$IP password=$PASSWORD"
relation-set db_host=$IP password=$PASSWORD
